2024-04-04 12:17:35 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_VIEWER- Root] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjU5NTQwNTE3MTQ2NjUyNTE0MDM=' \
-d ''
2024-04-04 12:17:35 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_VIEWER- Root][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 6d7efdde-fa62-40ac-8ccc-06d38c37f607'\
-H 'Cookie: RecentLogin=; TCSESSIONID=E909A33A1441DBCD41BDD5147973A867'\
-H 'Content-Length: 114'\
-H 'Authorization: Basic OjU5NTQwNTE3MTQ2NjUyNTE0MDM=' \
-d '{"parentProject": {"locator": " Root"}, "name": "process", "id": "UZMDNr0RFMl", "copeAllAssociatedSettings": true}' 

2024-04-04 12:17:35 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id ' Root'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m