2024-04-04 12:17:34 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_DEVELOPER-\u04337578970] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjU5NTQwNTE3MTQ2NjUyNTE0MDM=' \
-d ''
2024-04-04 12:17:34 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_DEVELOPER-\u04337578970][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: e011795b-4412-4b9f-a716-3b2ea82ee757'\
-H 'Cookie: RecentLogin=; TCSESSIONID=CA34D9AC14E00770C9EBEA0F44C730FE'\
-H 'Content-Length: 119'\
-H 'Authorization: Basic OjU5NTQwNTE3MTQ2NjUyNTE0MDM=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "commercial", "id": "\u04337578970", "copeAllAssociatedSettings": true}' 

2024-04-04 12:17:34 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "√ê¬≥7578970" is invalid: contains non-latin letter '√ê¬≥'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m