2024-04-04 12:17:35 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN-Root] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjU5NTQwNTE3MTQ2NjUyNTE0MDM=' \
-d ''
2024-04-04 12:17:35 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN-Root][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: ded5cef3-eb18-4ccd-913a-0b78f0931577'\
-H 'Cookie: RecentLogin=; TCSESSIONID=D5A787485937869B644C5F9201459B84'\
-H 'Content-Length: 110'\
-H 'Authorization: Basic OjU5NTQwNTE3MTQ2NjUyNTE0MDM=' \
-d '{"parentProject": {"locator": "Root"}, "name": "task", "id": "OWJfqh4qrWG", "copeAllAssociatedSettings": true}' 

2024-04-04 12:17:35 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id 'Root'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m