2024-04-02 20:36:58 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_VIEWER-_Root4] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjQwOTU3ODkyMzU3NzU2NDM0OTc=' \
-d ''
2024-04-02 20:36:58 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_VIEWER-_Root4][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: a857f69e-7b43-4d2e-8b44-2f4682da0d51'\
-H 'Cookie: RecentLogin=; TCSESSIONID=E2A2BAE22F2D43F4F5C0BB1E334B3794'\
-H 'Content-Length: 117'\
-H 'Authorization: Basic OjQwOTU3ODkyMzU3NzU2NDM0OTc=' \
-d '{"parentProject": {"locator": "_Root4"}, "name": "important", "id": "I3b_Kx1AjBV", "copeAllAssociatedSettings": true}' 

2024-04-02 20:36:58 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id '_Root4'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m