2024-04-04 12:41:23 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-tpCi 656] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjM4NzAyODQzODA0MjQ1NTUzMTM=' \
-d ''
2024-04-04 12:41:23 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-tpCi 656][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 6df88e44-8475-4a95-8292-0187f5bf9919'\
-H 'Cookie: RecentLogin=; TCSESSIONID=964160E3E5996B785F9DA02B71E7544A'\
-H 'Content-Length: 112'\
-H 'Authorization: Basic OjM4NzAyODQzODA0MjQ1NTUzMTM=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "actually", "id": "tpCi 656", "copeAllAssociatedSettings": true}' 

2024-04-04 12:41:23 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "tpCi 656" is invalid: contains unsupported character ' '. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m