2024-04-04 12:41:24 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_VIEWER-_Root4] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjM4NzAyODQzODA0MjQ1NTUzMTM=' \
-d ''
2024-04-04 12:41:24 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_VIEWER-_Root4][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 2f0b43bf-16a8-4a5a-b662-7bc116d2f5e3'\
-H 'Cookie: RecentLogin=; TCSESSIONID=53B99C2A60933C252898317E911C528A'\
-H 'Content-Length: 111'\
-H 'Authorization: Basic OjM4NzAyODQzODA0MjQ1NTUzMTM=' \
-d '{"parentProject": {"locator": "_Root4"}, "name": "hit", "id": "BuHfCPg025z", "copeAllAssociatedSettings": true}' 

2024-04-04 12:41:24 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id '_Root4'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m