2024-03-31 20:54:22 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN-_Root4] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjE2OTcxMTQxODIxOTA0NjI4NjA=' \
-d ''
2024-03-31 20:54:22 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN-_Root4][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 4ac44359-a5a2-40ef-9c8c-e2452f69a05e'\
-H 'Cookie: RecentLogin=; TCSESSIONID=03B1DA66D3FDB9565BADBB967E79E243'\
-H 'Content-Length: 117'\
-H 'Authorization: Basic OjE2OTcxMTQxODIxOTA0NjI4NjA=' \
-d '{"parentProject": {"locator": "_Root4"}, "name": "everybody", "id": "LZZfNEKSP41", "copeAllAssociatedSettings": true}' 

2024-03-31 20:54:22 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id '_Root4'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m